[build]
  command = "npm ci && npm run build:css && hugo --gc --minify"
  publish = "public"

  [build.environment]
    HUGO_VERSION = "0.125.7" # Или ваша версия
    NODE_VERSION = "20.11.1" # Или ваша версия
